name: 'ssh-cloudflared-tunnel'
inputs:
  password:
    required: true
  token:
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.password }}
    - ${{ inputs.token }}
